spring:
  config:
    activate:
      on-profile: production

logging:
  level:
    root: WARN
    com.github.diegogrlima.reservaai: INFO
    org.springframework: WARN
    org.hibernate: WARN
  file:
    name: ${LOG_FILE:logs/reserva-ai.log}
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
